sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src/tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=allure-results/**,allure-report/**,playwright-report/**,test-results/**,node_modules/**,**/*.png,**/*.webm,**/*.zip